### ISSUE TITLE
"Report a bug with Netplan" link 404s

### ISSUE THREAD

**Issue by OddBloke** [canonical-websites/netplan.io#15]
## Process

* Click the link

## Current and expected result

Expect: able to file a bug

Actual: 404

**Comment by cyphermox** [comment]
I'm including a fix for this in https://github.com/canonical-websites/netplan.io/pull/16

**Comment by powersj** [comment]
Both report a bug pages are working as expected, this can be closed.
Report a bug with this site  --> takes user to github.com
Report a bug with Netplan  --> takes user to launchpad.com
