### ISSUE TITLE
"Report a bug with Netplan" link (footer template) returns 404 Not found

### ISSUE THREAD

**Issue by tomreyn** [canonical-websites/netplan.io#17]
## Summary

At the very bottom of http://netplan.io/ there are some web links. One of them, titled "Report a bug with Netplan" points to https://github.com/canonicalltd/netplan/issues/new - an unavailable location since the GitHub issue tracker is disabled (now?).

## Process

- Access http://netplan.io/
- Scroll to bottom of page
- Click on "Report a bug with Netplan"

## Current and expected result

The location the "Report a bug with Netplan" text link points to returns a GitHub styled 404 error.
The location it points to should present the current Netplan issue tracker.

## Screenshot

(not relevant, so not included)

**Comment by powersj** [comment]
Both report a bug pages are working as expected, this can be closed.
Report a bug with this site  --> takes user to github.com
Report a bug with Netplan  --> takes user to launchpad.com

Thanks!
