### ISSUE TITLE
Split examples page into seperate how-to/FAQ and examples pages

### ISSUE THREAD

**Issue by powersj** [canonical-websites/netplan.io#19]
## Summary

The Examples page consists of lots of questions and answers of how to do various scenarios. I would like to suggestion breaking this up into two pages:

First, a How-To/FAQ page which has the current content.

Second, an examples page, which is contains real examples of specific features. For example, how to do bonding of each type, how to do a bridge, how to do vlans, etc. I have a collection of [various configs](https://github.com/powersj/netplan-test/tree/master/configs) that I have used for testing and I would like to have something similar on the example page.

**Comment by cyphermox** [comment]
This is just stop-gap. We'll drop the FAQ part, and simply have that as askubuntu questions; but examples should end up here.
