### ISSUE TITLE
https://netplan.io/examples#bridging is not a stand-alone example

### ISSUE THREAD

**Issue by vorlonofportland** [canonical-websites/netplan.io#48]
## Summary

The example given at https://netplan.io/examples#bridging shows a complete netplan yaml which does not validate, because it defines a bridge which references an ethernet interface which is not declared.

This led to https://askubuntu.com/questions/1096089/netplan-bridge-issue/1098585#1098585 asked by a user.

The example given for a bridge should be as simple as possible but no simpler.

**Comment by cyphermox** [comment]
This is fixed now.

**Comment by tbille** [comment]
Closing since fixed
